### DISCUSSION TITLE
IMU configuration

### DISCUSSION THREAD

**Discussion by Fabien-B** [paparazzi/paparazzi#3189] [General]
Hi @fvantienen, @gautierhattenberger 
I think we should discuss about the IMU/sensors configurations.
This message is also supported by @FlorianSan :smiley: 

## the problems

- the naming:
When `IMU_BODY_TO_IMU_[PHI/THETA/PSI]` are defined, `IMU` does not refers to the sensor, but more to the reference frame of all sensors. Therefore, I think it could be named `BODY_TO_BOARD`.

- changing meaning:
Before the following line, the `body_to_sensor` field seems to contain a _board_to_sensor_ rotation matrix. (can you confirm?)
It makes it harder to understand the code.
https://github.com/paparazzi/paparazzi/blob/9c1e21d0ceda65c4b17224e6a76ac066df94c37d/sw/airborne/modules/imu/imu.c#L386-L387

- over-complicated retro-compatibility:
There is more than 130 lignes of macro preprocessing for the configuration in imu.c. Don't you think it's too much?
Can we drop the old way of defining the configuration and focus on the new way?

- As much as I like when it's unambiguous, the configuration for a sensor is awfully long:
`<define name="ACCEL_CALIB" value="{{.abi_id=24, .calibrated={.neutral=true, .scale=true, .rotation=true},.neutral={-10,-47,-130}, .scale={{36821,8142,5741},{60003,13319,9358}}, .body_to_sensor={{0,-16383,0,16383,0,0,0,0,16382}}}}"/>`
Most of this line is generated by the calibration tool so it's ok for me, but adding the `body_to_sensor` field is tedious.
Maybe this field should be separated from the rest, especially because:
    - it's not something that will change a lot,
    - I suspect the name is wrong at this time (cf 2nd point).
    - Writing a matrix is tedious. Could it be eulers angles ? Or quaternions ?

## the solutions

What can we do about that is up to discussions!

A possible solution is to write the rotations in a separated file that could be handled either by the airframe generator, or by the calibration tool.
This file would be an optional argument of `calibrate.py`. If present, the `body_to_sensor` part of the structure would also be generated, making the copy-paste easy again.
The rotation file could look like this:
``` YAML
# body to board rotation
board:
    phi: 45
    theta: 0
    psi: 0

# board to sensor rotations
sensors:
    - name: "accel"
      abi_id: 9
      # default orientation
    - name: "mag"
      abi_id: 3
      phi: 0
      theta: 0
      psi: 90
    - name: "external mag"
      abi_id: 3
      phi: 0
      theta: -90
      psi: 90
```
Using a file like this, the `body_to_imu_rmat` could entirely be removed from the code, leaving just the `body_to_sensor` fields, without the naming issue.

What do you think ?
